//
//  Api+Constants.swift
//  Basic
//
//  Created by Himanshu on 02/01/18.
//  Copyright © 2018 Himanshu. All rights reserved.
//

import Foundation
var base = "http://103.253.14.203/main/api/"
var baseDashboard = "http://103.253.14.203/main/api/"
enum Apis {
    //static let base = "http://103.253.14.203/main/api/"
    //static let baseDashboard = "http://103.253.14.203/main/api/"
    //static let baseDashboard = "http://originida.ddns.net:8686/main/api/"
	static let signIn = "login"
	static let signUp = "signup"
	static let forgotPassword = "forgotPassword"
    static let resetPassword = "changePassword"
    static let updatePushNotificationSetting = "updatePushNotificationSetting"
    static let getPushNotification = "getPushNotification"
    static let getEmpLeave = "getEmpLeave"
    static let getTop10Sales = "getTop10Sales"
    static let getPoor10Sales = "getPoor10Sales"
    static let getTop10TD = "getTop10TD"
    static let getPoor10TD = "getPoor10TD"
    static let updateProfile = "updateProfile"
    static let siteListing = "siteListing?siteCode="
    static let staffSiteListing = "staffSiteListing?siteCode="
    static let getStaffMember = "getStaffMemberList"
    static let getSaloonList = "getSaloonList?siteCode="
    static let getSaloondetail = "getSallonDetail?siteCode="
    static let getSiteListingOption = "siteListing?siteCode="
    static let deactivateStaffMember = "UpdateEmployeeDeactivate"
    static let updateSiteListingOption = "UpdateEmployeeSiteListing"
    static let getOutletSales = "getOutletSales"
    static let markAttendance = "markAttendance"
    static let updateProfilePicture = "EmployeeProfilePicture"
    static let getHistoryAndPastJobs = "HistoryAndPastJobs"
    static let getTaskList = "getTaskList"
    static let getTaskType = "getTaskType?siteCode="
    static let getCustomerList = "getcustomerList?siteCode="
    static let updateTaskPicture = "UpdateTaskPicture"
    static let getDepartmentList = "getDepartmentList?siteCode="
    static let getServiceType = "getService?siteCode="
    static let getTaskDetail = "getTaskDetail?taskID="
    static let deletetask = "deleteTask"
    static let getNotificationList = "getNotificationList"
    static let updateTaskStatus = "updateTaskStatus"
    static let createWorkSchedule = "createWorkSchedule"
    static let getWorkScheduledList = "getListOfWorkSchedule?userID="
    static let getWorkScheduleType = "workScheduleType?siteCode="
    static let taskTypeListingOption = "getTaskType?siteCode="
    static let getCustomerSite = "getCustomerSite?siteCode="
    static let getGender = "gender?siteCode="
    static let getRaces = "race?siteCode="
    static let getNationality = "nationality?siteCode="
    static let getReligion = "religion?siteCode="
    static let getMaritalStatus = "maritalStatus?siteCode="
    static let employeeDesignation = "employeeDesignation?siteCode="
    static let skillSets = "skillSets?siteCode="
    static let employeeSecurity = "employeeSecurity?siteCode="
    static let createEmployee = "createEmployee"
    static let getAppointmentGroupList = "getAppointmentGroupList?siteCode="
    static let targetType = "TargetType?siteCode="
    static let targetPeriod = "TargetPeriod?siteCode="
    static let createSalaryTargerApp = "createSalaryTargetAppt"
    static let createEmployeeSetting = "createEmployeeSetting"
    static let updateEmployee = "updateEmployee"
    static let UpdateSalaryTargetAppt = "UpdateSalaryTargetAppt"
    static let getAppliedLeaveList = "getAppliedLeaveList"
    static let getLeaveType = "getLeaveType?siteCode="
    static let applyLeave = "applyLeave"
    static let leaveApprovedRejected = "LeaveApprovedRejected"
    static let updateLeaveStatus = "updateLeaveStatus"
//    static let attananceReport = "AttananceReport"
    static let attananceReport = "getLastCheckInOut"
    static let updateWorkSchedule = "UpdateWorkSchedule"
    static let customerAppointment = "customerAppointment?siteCode="
    static let markArrived = "customerAppointment"
    static let empAppDashBoard = "empAppDashBoard?siteCode="
    static let getBankInAmount = "getBankInAmount"
    static let empAppCashVoucher = "empAppCashVoucher"
    static let createTaskComments = "createTaskComments"
    static let getBankInAmountBankIn = "getBankInAmount?siteCode="
    static let salesCommsion = "getSalesCommissionByStaff"
    static let senseGetStaffMList = "sense_getStaffMList"
    static let getCustomerAppointmentList2 = "GetCustomerAppointmentList2"
}

