workflows:
  employeeapp:
    name: employeeapp
    labels:
      - QA
      - PRODUCTION
    instance_type: mac_mini_m2
    max_build_duration: 60
    inputs:
      name:
        description: Input description
        default: Codemagic
    environment:
      groups:
        - group_name
      vars:
        PUBLIC_ENV_VAR: "value here"
      flutter: stable
      xcode: latest
    cache:
      cache_paths:
        - ~/.pub-cache
    triggering:
      events:
        - push
      branch_patterns:
        - pattern: "*"
          include: true
          source: true
      cancel_previous_builds: false
    scripts:
      - echo "Hello, $name"
      - echo "Running build..."
      # Add your actual build commands here
    artifacts:
      - build/**/outputs/bundle/**/*.aab
    publishing:
      email:
        recipients:
          - yoonus@sequoia-asia.com
      scripts:
        - echo "Post-publish script"